### PR TITLE
Conflict mods

### PR DESCRIPTION
**Pull request by pshriwise**
Altering the conflicts lesson to keep both lines. This was the only way I was able to get a successful continuation of the branch without further merge conflicts.

### CODE REVIEW

**Comment by sstevens2** [comment]
Maybe we want to leave a note for the possible online learner and instructor that this may not always work depending on how they solve the conflict

**Comment by pshriwise** [comment]
I think that's the best solution. I'll make that a call-out in the lesson. 

I was going to say I'd close this PR and do it in a separate PR, but I think that really they should keep both lines so I'll just add that call-out to this PR.

**Comment by sstevens2** [comment]
Looks good to me!  I can go ahead and merge this if you are happy with it @pshriwise

**Comment by pshriwise** [comment]
As happy w/ it as I'll ever be :smiley:

**Pull request merged**
